apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-scripts
  namespace: loadtest
data:
  locustfile.py: |
    import time
    import random
    from locust import HttpUser, task, between

    class FirecornUserTest(HttpUser):

        wait_time = between(0.5, 3.0)
        names = ["Randy Savage", "Bubb Rub", "Steve Austin", "Rick Flair", "Count Chocula", "Technoviking", "Nic Cage"]

        @task(1)
        def create_user(self):
            mutation = """
            mutation {
                createUser(userDetails: {
                    name: "%s",
                    sex: "%s",
                    address: "%s",
                    phoneNumber: "%s",
                })
                {
                    id
                    name
                    address
                }
            }
            """ % (
                self.names[random.randint(0, len(self.names))],
                ['male','female'][random.randint(0,1)],
                "123 Main St. Awesomeville USA",
                random.randint(0000000000,9999999999),
            )
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="CreateUser",
                headers={
                    "Accept": "application/graphql",
                },
                json={"query": mutation},
            )

        @task(2)
        def query_users(self):
            query = """
            query {
                getUsers {
                    name
                    address
                }
            }
            """
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="GetUsers",
                headers={
                    "Accept": "application/graphql",
                },
                json={"query": query},
            )

        @task(3)
        def create_post(self):
            # This should a random user
            mutation = """
            mutation createPost {
            createPost(postDetails: {
                userId: %d,
                title: "Post number %d",
                body: "Post body number %d"
            })
            {
                id
                body
            }
            }
            """ % (
                random.randint(0,100),
                random.randint(0,1000),
                random.randint(0,1000)
            )
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="CreatePost",
                headers={
                    "Accept": "application/graphql",
                },
                json={"query": mutation},
            )

        @task(2)
        def get_posts(self):
            query = """
            query {
                getPosts {
                    id
                    body
                }
            }
            """
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="GetPosts",
                headers={
                    "Accept": "application/graphql",
                },
                json={"query": query},
            )

        @task(5)
        def create_comment(self):
            mutation = """
            mutation createComment {
                createComment(commentDetails: {
                    userId: %d,
                    postId: %d,
                    body: "Comment number %d"
                })
                {
                    id
                    body
                }
            }
            """ % (
                random.randint(0,100),
                random.randint(0,100),
                random.randint(0,1000)
            )
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="CreateComment",
                headers={"Accept": "application/graphql",},
                json={"query": mutation}
            )

        @task(2)
        def get_comments(self):
            query = """
            query {
                getComments {
                    id
                    body
                }
            }
            """
            _ = self.client.post(
                "http://api.firecorn.apps.dev.agiledagger.io/",
                name="GetPosts",
                headers={
                    "Accept": "application/graphql",
                },
                json={"query": query},
            )