apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: locust-worker
    app: locust-worker
  name: locust-worker
  namespace: loadtest
spec:
  replicas: 2
  selector:
    matchLabels:
      role: locust-worker
      app: locust-worker
  template:
    metadata:
      labels:
        role: locust-worker
        app: locust-worker
    spec:
      containers:
      - image: quay.lab.agiledagger.io/mmurphy/locust:0.1.1
        imagePullPolicy: IfNotPresent
        name: worker
        command: ["sh","-c","locust"]
        args: ["--worker", "--master-host=locust-master"]
        volumeMounts:
          - mountPath: /home/
            name: locust-scripts
          - mountPath: /tmp
            name: shared-volume
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: cm-scripts
      - name: shared-volume
        emptyDir: {}