apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: locust-master
    app: locust-master
  name: locust-master
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      role: locust-master
      app: locust-master
  template:
    metadata:
      labels:
        role: locust-master
        app: locust-master
    spec:
      containers:
      - image: quay.lab.agiledagger.io/mmurphy/locust:0.1.1
        imagePullPolicy: IfNotPresent
        name: master
        command: ["sh","-c","locust"]
        args: ["--master"]
        volumeMounts:
          - mountPath: /home/
            name: locust-scripts
          - mountPath: /tmp
            name: shared-volume
        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-1
        - containerPort: 8089
          name: web-ui
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: locust-scripts
        configMap:
          name: cm-scripts
      - name: shared-volume
        emptyDir: {}