apiVersion: v1
kind: Secret
metadata:
  name: mmurphy-smigbot-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmxhYi5hZ2lsZWRhZ2dlci5pbyI6IHsKICAgICAgImF1dGgiOiAiYlcxMWNuQm9lU3R6YldsblltOTBPbGhUTTBZek9VUlJURXRJVnpnNFNGUTNTMEZJTVVnNFR6SlVUMGs0TkRaVFVrdzBRMDR4VkV4WlRGQTBSRUk0VGpaSVMxZExPRFJXTjFCQ1RWcFlVbFE9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson